USE CUSTOMER_SHOPPING_BEHAVIOUR




SELECT TOP 10 * FROM dbo.CUSTOMER_SHOPPING_BEHAVIOR


-- Q1. What is the total revenue generated by male vs. female customers?

SELECT GENDER,
	   SUM(PURCHASE_AMOUNT) AS REVENUE
FROM CUSTOMER_SHOPPING_BEHAVIOR
GROUP BY GENDER

-- Q2. Which customer used a discount but still spent more than the average purchase amount? 
SELECT CUSTOMER_ID,
	   PURCHASE_AMOUNT
FROM CUSTOMER_SHOPPING_BEHAVIOR
WHERE DISCOUNT_APPLIED = 'YES'
	  AND PURCHASE_AMOUNT >= (SELECT AVG(PURCHASE_AMOUNT) FROM customer_shopping_behavior)

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5 ITEM_PURCHASED AS PRODUCT,
	   ROUND(AVG(REVIEW_RATING),2) AS AVG_REVIEW_RATING
FROM customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY AVG_REVIEW_RATING DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT ROUND(AVG(PURCHASE_AMOUNT),2) AS AVG_PURCHASE_AMOUNT,
		SHIPPING_TYPE
FROM customer_shopping_behavior
WHERE Shipping_Type IN ('STANDARD', 'EXPRESS')
GROUP BY Shipping_Type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT SUBSCRIPTION_STATUS,
		ROUND(AVG(PURCHASE_AMOUNT),2) AS AVERAGE_PURCHASE_AMOUNT,
		ROUND(SUM(PURCHASE_AMOUNT),2) AS TOTAL_REVENUE,
		COUNT(Customer_ID) AS TOTAL_CUSTOMERS
FROM customer_shopping_behavior
GROUP BY Subscription_Status
ORDER BY TOTAL_REVENUE, AVERAGE_PURCHASE_AMOUNT DESC

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 Item_Purchased,
		ROUND(100*(SUM(CASE WHEN Discount_Applied = 'YES' THEN 1 ELSE 0 END))/COUNT(*),2) AS DISCOUNT_RATE
FROM customer_shopping_behavior
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH CUSTOMER_TYPE AS (
SELECT CUSTOMER_ID,
		PREVIOUS_PURCHASES,
CASE
	WHEN PREVIOUS_PURCHASES = 1 THEN 'NEW'
	WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'RETURNING'
	ELSE 'LOYAL'
	END AS CUSTOMER_SEGMENT
FROM customer_shopping_behavior
)
SELECT CUSTOMER_SEGMENT, COUNT(*) AS NO_OF_CUSTOMERS
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT;

--Q8. What are the top 3 most purchased products within each category? 
WITH ITEM_COUNTS AS(
SELECT ITEM_PURCHASED,
	   CATEGORY,
	   COUNT(CUSTOMER_ID) AS TOTAL_ORDERS,
	   ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY COUNT(CUSTOMER_ID) DESC) AS ITEMS_RANK
FROM customer_shopping_behavior
GROUP BY Item_Purchased, Category)

SELECT ITEMS_RANK,ITEM_PURCHASED, CATEGORY, TOTAL_ORDERS
FROM ITEM_COUNTS
WHERE ITEMS_RANK <= 3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT SUBSCRIPTION_STATUS,
		COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM customer_shopping_behavior
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status

--Q10. What is the revenue contribution of each age group? 

SELECT AGE_GROUP,
	   SUM(PURCHASE_AMOUNT) AS REVENUE_CONTRIBUTION
FROM CUSTOMER_SHOPPING_BEHAVIOR
GROUP BY AGE_GROUP
ORDER BY REVENUE_CONTRIBUTION DESC